name: CI/CD for Silent Hill Site

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Получение кода
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Линтинг HTML
    - name: Lint HTML
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install -g htmlhint
    - run: htmlhint "index.html"  

    # Шаг 3: Линтинг CSS
    - name: Lint CSS
      run: |
        npm install -g stylelint stylelint-config-standard
        stylelint "style.css" --config .stylelintrc.json

    # Шаг 4: Линтинг JavaScript 
    - name: Lint JS
      run: npm install -g eslint
    - run: eslint "script.js" --fix-dry-run 

    # Шаг 5: Запуск Python тестов
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt

    - name: Run tests
      run: pytest tests/